version: '3'

services:
  redmine:
    image: redmine
    ports:
      - 23456:3000
    volumes:
      - /var/www/vhosts/devgiants.fr/projects.devgiants.fr/files/config:/usr/src/redmine/config
      - /var/www/vhosts/devgiants.fr/projects.devgiants.fr/files/public:/usr/src/redmine/public
      - /var/www/vhosts/devgiants.fr/projects.devgiants.fr/files/files:/usr/src/redmine/files
    environment:
      REDMINE_DB_MYSQL: mysql-container
      REDMINE_DB_PASSWORD: 53za05179wiB96q
    restart: always
    depends_on:
      - mysql-container

  mysql-container:
    image: mysql
    volumes:
      - /var/www/vhosts/devgiants.fr/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 53za05179wiB96q
    restart: always

networks:
  fixednet:
    driver: bridge
    ipam:
      config:
      - subnet: 172.25.0.0/24
